import Head from "next/head";
import React from "react";

export default function Home() {
	return (
		<div>
			<Head>
				<title>E-Pawn</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Dosis:wght@200;400;600;800&family=Nunito:wght@200;400;600;800&display=swap"
					rel="stylesheet"
				/>
			</Head>
			<p className="text-sm font-nunito">
				The quick brown fox jumps over the lazy dog
			</p>
			<p className="text-base font-nunito ">
				The quick brown fox jumps over the lazy dog
			</p>
			<p className="text-lg font-nunito ">
				The quick brown fox jumps over the lazy dog
			</p>
			<p className="text-xl font-nunito ">
				The quick brown fox jumps over the lazy dog
			</p>
			<p className="text-2xl font-nunito ">
				The quick brown fox jumps over the lazy dog
			</p>
			<p className="text-3xl font-nunito ">
				The quick brown fox jumps over the lazy dog
			</p>
		</div>
	);
}
